#!/bin/bash

#
# /etc/xdg/pacaur/config
#

# The following options are commented out with their default values listed.
# If you wish to use different values, uncomment and update the values.
builddir="${HOME}/Documents/Builds"    # build directory
#editor="${EDITOR:-vi}"                # PKGBUILD editor
editpkgbuild=false                     # edit PKGBUILD script
editinstall=false                      # edit install script
#fallback=true                         # pacman fallback to the AUR
clean=false                            # clean up after package install
cleandevel=false                       # clean up devel package
#secure=false                          # enhanced security
#sudoloop=false                        # prevent sudo timeout

