#!/usr/bin/env ruby

require 'json'
require 'rest-client'

APIKey = "d3d002e78d0e505d9573a51f29b9b53a"

class Metabox
  UploadURI = "http://metabox.it/uploads/create"

  def initialize key = nil
    @key = key
  end

  def upload path
    JSON.parse RestClient.post UploadURI, key: @key, file: File.open(path)
  rescue Exception
    nil
  end
end

path    = File.expand_path ARGV.join " "
metabox = Metabox.new APIKey

if File.exists? path
  result = metabox.upload path

  if result["success"]
    url = "http://dl.gs/#{result["upload"]["base_id"]}"
    puts url

    %x{printf "#{url}" | xsel -bi}
  else
    puts "Error: Could not upload file: #{result["message"]}."
  end
else
  puts "File does not exist."
end
