#!/bin/bash

OSD=true # Notify when the screenshot has been uploaded (requires imagemagick and libnotify)
name="`date +%s`.png" # The local file name of the screenshot

function save {
  case "$1" in
    selection)
      sleep 0.2
      `scrot -bs /tmp/$name 2> /dev/null`
      ;;
    desktop)
      `scrot -b /tmp/$name 2> /dev/null`
      ;;
    *)
      echo "Unknown type of screenshot."
      exit 1
      ;;
  esac

  if [ ! -f /tmp/$name ]; then
    echo "Screenshot was not taken. Aborting."
    exit 1
  fi
}

function upload {
  echo "Uploading $name."
  
  if [ $OSD ]; then # generate thumbnail (requires imagemagick)
    `convert -thumbnail 120x240 /tmp/$name /tmp/t$name`
  fi

  response=`curl -F file=@/tmp/$name -F key=d3d002e78d0e505d9573a51f29b9b53a http://dl.gs 2> /dev/null`
  
  if [[ $response == http* ]]; then
    `echo $response | tr -d '\n' | xsel -ip`
    echo "Upload complete - $response"
    
    if [ $OSD ]; then
      notify-send "Screenshot" "The screenshot has been uploaded." -i "/tmp/t$name"
    fi
  else
    echo $response
    exit 1
  fi
}

function delete {
  rm /tmp/$name

  if [ $OSD ]; then
    rm /tmp/t$name
  fi
}

save $1
upload
delete
